plugins {
    id 'java'
    id 'org.springframework.boot' version '4.1.0'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.spb'
version = '0.0.1-SNAPSHOT'
description = 'student-portal-backend'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(26)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation("org.springframework.data:spring-data-jpa:4.2.0-M1")
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    implementation("org.projectlombok:lombok:0.11.0")
    implementation("org.hibernate:hibernate-gradle-plugin:5.6.15.Final")
    implementation("org.postgresql:postgresql:42.7.13")
}

tasks.named('test') {
    useJUnitPlatform()
}
