spring.application.name=student-portal-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/student_portal
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

# JWT
jwt.secret=${JWT_SECRET:SpOWckrDvBtPVCYStKfZjRZdHbf2M2tJ4aW2bFLVqAt7nD4ZP41VEmr+4jSESwkza8Cb0LU7Guf4H5qQp1+u1g==}
jwt.expiration-ms=86400000